### ISSUE TITLE
How can I get the raw depth map and pose?

### ISSUE THREAD

**Issue by cdb0y511** [wh200720041/SSL_SLAM#14]
Hi, @wh200720041 
I find the ssl_slam use point cloud to do slam.
I wish it could provide poses for depth frame so that it can be used for reconstruction. It is possible to enable depth map and align poses together through ssl_slam? 
Is there any difference for RGB  align to depth map other vices?

**Comment by Zumbalamambo** [comment]
+1

**Comment by wh200720041** [comment]
Hi @cdb0y511  and @Zumbalamambo 

Thanks for posting question here.

I would like to recommend two ways

You may use pcd save function provided by PCL
pcl::io::savePCDFile( "cloud.pcd", *map, true );
You can add this function at mapping thread. However, you need to recompile the code

A faster way is to use ros_pcl
rosrun pcl_ros pointcloud_to_pcd input:=/map
You may also check the ros official website for more information
http://wiki.ros.org/pcl_ros

This function will also be updated in the new project https://github.com/wh200720041/SSL_SLAM2, I am still working on it

Regards
Han

**Comment by cdb0y511** [comment]
Hi, @wh200720041 , thanks for the reply.
I have managed to save point cloud through rosrun pcl_ros pointcloud_to_pcd input:=/map.
However, the typical reconstruction methods need 3 inputs, the RGB frame, the depth frame, and the poses.
1. Can SSL_SLAM output these three?
2. In my experience, for l515 align the depth map to RGB frame will introduce extra errors, so I prefer RGB frame to align to the depth frame. But I am not sure if SSL_SLAM2 utilizes the photometric information to do slam, it will have a big difference between these two settings.

**Comment by wh200720041** [comment]
Hi @cdb0y511 

1. The poses can be found in /odom,  the rgb and depth images can be found in /camera/color/image_raw /camera/depth/image_raw
2. Kindly note that SSL_SLAM is a LiDAR SLAM rather than Visual SLAM. the pose is not calculated based on photometric error.
Thanks

**Comment by cdb0y511** [comment]
That's great. I will try it later.
Thanks again.
