### ISSUE TITLE
This is a question to the developers, not even an issue

### ISSUE THREAD

**Issue by akdba0207** [wh200720041/ssl_slam#15]
Hi, I'm very grateful to learn L515 SLAM from your paper and github package

and you said you are running your code 20Hz in NUC, 30Hz in PC

Is this number related to the fps parameters in rs_camera.launch file in the launch folder?

Thanks,

**Comment by wh200720041** [comment]
Hi @akdba0207 

The speed is evaluated based on computing time / frame, it is not related to the fps parameters in rs_camera.launch

**Comment by akdba0207** [comment]
Understood. 

Many Thanks !
